### ISSUE TITLE
mobs can traspass closed doors even with mmaps on

### ISSUE THREAD

**Issue by Aokromes** [jackpoz/TrinityCore#10]
Again example on utgarde pinacle, you can call final boss from entrance.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14120

**Comment by GeneralSaurfang** [comment]
As mmaps doesn't seem much likely to take gameobjects into account anytime soon, can we have the blizzlike fix Aokromes suggested implemented?

Even when and if mmaps manage to fix this problem, this fix should enforce the encounter to remain inside the room. It will still remain useful.
