### ISSUE TITLE
.debug hostil

### ISSUE THREAD

**Issue by Aokromes** [jackpoz/TrinityCore#22]
The current output is:

Hostil reference list of playername (guid playerguid)
1.   Mindless Servant   (guid 251224)  - threat 6921.952637
End of hostil reference list.

IMHO it can be better to be:
Hostil reference list of playername (guid playerguid)
1.   Mindless Servant   (DB GUID: 126135, current GUID: 251423.)  - threat 6921.952637
End of hostil reference list.

**Comment by jackpoz** [comment]
move it to tc repo
