### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by jackpoz** [jackpoz/TrinityCore#41]
Log stats about anything happening with very low overhead
- [x] the data should be written at the rate of a configurable timer ~~and configurable event size~~ using the logging io_service
- [x] the data should be queued in a thread-safe way and sent in batches
- [x] add "realm" as input data tag
 - realm.Name in worldserver, passed as parameter in Initialize(). The tag is ignored if empty (i.e. for authserver)
- [x] ingame events like InstanceReset could be handled as Annotations http://docs.grafana.org/reference/annotations/
- [x] some data could be collected at specified time ranges with a lambda returning a std::string as value
- [x] Player login/logout should be logged to a player_events table. LogEvent() should accept an optional event category, events by default. Each object should have its own <category>_events table, maybe with a config option to enable/disable a whole category.
- [ ] Map load/unload should be logged to their own map_events table. Maybe tile load/unload too. Player added/removed, creature added/removed.
- [x] Pathfinding queries should be logged in mmap_events.
- [x] thread-unsafe stats like Online Players should be retrieved from worldupdateloop with a sStatsLogger->Update() method
 - std::function / std::bind(...., &this) could be used to pass to StatsLogger a Func<World, List<Metrics>> to get metrics like player count, etc

**Comment by jackpoz** [comment]
- https://s3.amazonaws.com/influxdb/influxdb_0.9.4.2_amd64.msi
- https://docs.influxdata.com/influxdb/v0.9/guides/writing_data/

**Comment by jackpoz** [comment]
![wdxmk](https://cloud.githubusercontent.com/assets/1153754/13061231/06a69bba-d437-11e5-8984-de7667713e25.jpg)

**Comment by jackpoz** [comment]
http://play.grafana.org/ has looots of examples

**Comment by DDuarte** [comment]
Not sure how to pass the realm info to the logger. The first event/value is being logged long before the realms are initialized (https://github.com/TrinityCore/TrinityCore/blob/3.3.5-Graphana/src/server/worldserver/Main.cpp#L133 vs https://github.com/TrinityCore/TrinityCore/blob/3.3.5-Graphana/src/server/worldserver/Main.cpp#L200)

**Comment by jackpoz** [comment]
LoadRealmInfo() looks like it's called before starting to load all the database tables, we could move the sStatsLogger initialization after that line. This is mostly useful only for debug builds where it can take from 1 to few minutes between process start and world initialized.

**Comment by DDuarte** [comment]
Perhaps we can have 3 events: worldserver start, worldserver ready (starts accepting connections) and worldserver shutdown.

**Comment by jackpoz** [comment]
the "worldserver ready" is currently logged as "World initialized" https://github.com/TrinityCore/TrinityCore/blob/3.3.5-Graphana/src/server/game/World/World.cpp#L1897 but could be moved after port bindings have been setup, so around https://github.com/TrinityCore/TrinityCore/blob/3.3.5-Graphana/src/server/worldserver/Main.cpp#L249 .

**Comment by DDuarte** [comment]
Realm name added in 879d4b6bb78f5276136efd0a8597794a2a6b9046

**Comment by jackpoz** [comment]
I ran out of tasks to do here, we can go on discussing it at https://github.com/TrinityCore/TrinityCore/issues/15075 . Almost the only thing left to do is fill TC sources with metrics/events logs

**Comment by DDuarte** [comment]
Can be closed :P
