### ISSUE TITLE
.gobj target improve

### ISSUE THREAD

**Issue by Aokromes** [jackpoz/TrinityCore#6]
How about change:

Selected object:
[Call Tram] GUID: 42867 ID: 194914
X: 2277.419922 Y: 298.692993 Z: 419.246002 MapId: 603
Orientation: 3.141590
Phasemask 1

Into:
Selected object:
[Call Tram] GUID: 42867 ID: 194914
X: 2277.419922 Y: 298.692993 Z: 419.246002 MapId: 603
Orientation: 3.141590
Flags: (gameobject_template.flags field)
Phasemask 1 Spawnmask 3 
AIName:  ScriptName:

**Comment by jackpoz** [comment]
move it to tc repo
