### ISSUE TITLE
GUID Warning

### ISSUE THREAD

**Issue by jackpoz** [jackpoz/TrinityCore#77]
- [x] Respawn.GuidWarnLevel should log the guid type (creature, gameobject, item, player) and maybe something more useful like mapid or so.
- [x] Add a chat command to list the current top guid of every type https://github.com/TrinityCore/TrinityCore/commit/7421ccaf7eb134f549ad3734a815397216d020ed
- [x] Ask how come guid recycling is not implemented (client-side or server-side issues ?)
  - It seems to have been removed with dynamic spawning

**Comment by jackpoz** [comment]
@TheWinchesters https://github.com/TrinityCore/TrinityCore/commit/7421ccaf7eb134f549ad3734a815397216d020ed adds a new chat command ".debug guidlimits" to see the current values for each map, maybe it can help figure out why it's growing so fast

**Comment by TheWinchesters** [comment]
I will apply that commit tonight and see what is going on.
Today, again, after almost 5 days online, server will be restarted in a couple of hours because of the same warning.

**Comment by TheWinchesters** [comment]
I have used the command.
Maps 0, 1, 531, 571 are incrementing guids over time.
As example:
Server uptime: 29 minutes | map 571 has Highest guid creature: 52014
Server uptime: 32 minutes | map 571 has Highest guid creature: 59492
Server uptime: 33 minutes | map 571 has Highest guid creature: 63022

More than something growing so fast, looks like it a matter of time to reach guid warn level.

I will update this comment every day to see how much guids grows over time.

**Comment by jackpoz** [comment]
what's your Wintergrasp.Enable config value ?

**Comment by TheWinchesters** [comment]
Wintergrasp.Enable = 0

Server uptime:  1 hour 24 min
Map Id: 530 'Terrallende' Highest Guid Creature: 55897 GameObject: 21284
Map Id: 1 'Kalimmdor' Highest Guid Creature: 55578 GameObject: 20197
Map Id: 0 'Eastern Kingdoms' Highest Guid Creature: 58390 GameObject: 25753
Map Id: 571 'Nothrend' Highest Guid Creature: 151003 GameObject: 42269

Having in mind how fast Highest Guid Creature grows over time in Map 571, I bet that is the one that triggers GuidWarnLevel.

**Comment by jackpoz** [comment]
what are you GridUnload and BaseMapLoadAllGrids configs ?

**Comment by TheWinchesters** [comment]
GridUnload = 1
BaseMapLoadAllGrids = 0

Server uptime: 10 hours 12 min
Map 571 (the highest one) has Highest Guid Creature: 1149126
If that is the highest guid in 10 hours, that explains why the restart occurs if server uptime is 4 o 5 days.

**Comment by jackpoz** [comment]
You could try setitng GridUnload = 0. worldserver will use more RAM this way but it should use much less GUIDs.

**Comment by jackpoz** [comment]
I set GridUnload = 0 on the test realm too (it was already like that until we tested the Honor Hold event bug) in case you want to test anything particular there

**Comment by jackpoz** [comment]
@TheWinchesters any update about this issue ?
